<?php  echo $this->pageTitle("Impressum"); ?>

    Impressum Seite. Dies ist ein Typoblindtext. An ihm kann man sehen, ob alle Buchstaben da sind und wie sie aussehen. Manchmal benutzt man Worte wie Hamburgefonts, Raf.genduks oder Handgloves, um Schriften zu testen. Manchmal Sätze, die alle Buchstaben des Alphabets enthalten - man nennt diese Sätze »Pangrams«. Sehr bekannt ist dieser.
    Dies ist ein Typoblindtext. An ihm kann man sehen, ob alle Buchstaben da sind und wie sie aussehen. Manchmal benutzt man Worte wie Hamburgefonts, Raf.genduks oder Handgloves, um Schriften zu testen. Manchmal Sätze, die alle Buchstaben des Alphabets enthalten - man nennt diese Sätze »Pangrams«. Sehr bekannt ist dieser.
        Dies ist ein Typoblindtext. An ihm kann man sehen, ob alle Buchstaben da sind und wie sie aussehen. Manchmal benutzt man Worte wie Hamburgefonts, Raf.genduks oder Handgloves, um Schriften zu testen. Manchmal Sätze, die alle Buchstaben des Alphabets enthalten - man nennt diese Sätze »Pangrams«. Sehr bekannt ist dieser.
    

<?php
/*
$rss = simplexml_load_file('http://www.netzwelt.de/feed/news/all/RSS2.0.xml');
$maxitems = 7;

print ($rss->channel->title);
print ("\n\r");
foreach ($rss->channel->item as $item) {

   $ta = explode( ' ', $item->pubDate );
   print $ta[0] . " " . $ta[1] . " " . $ta[2] . "\t";

   print ($item->title);
   // print ($item->description);
   print ("\r");
   $maxitems--;
   if (!$maxitems) exit;
} 
*/
?>